### ISSUE TITLE
Invoking a module on a large file takes a long time

### ISSUE THREAD

**Issue by russellbanks** [VirusTotal/yara-x#157]
Using `yara_x::mods::invoke::<PE>()` on a large file takes a long time. I've used Android Studio Canary to test this which is ~1.2gb in size. For me, it takes ~70 seconds to invoke the function on that file.

**Comment by plusvic** [comment]
That 1.2GB files is a PE file? Can you share the file somehow?

**Comment by plusvic** [comment]
I got the the file from https://developer.android.com/studio/preview, and ran:

```
yr dump -m pe android-studio-2024.1.1.12-windows.exe
```

It took 6.5 seconds in my laptop with the release version, and 56 seconds with the debug version. So, I guess the problem is that you are using the debug version. The debug version in Rust program is usually very slow when compared with the release version.

**Comment by russellbanks** [comment]
Thanks for checking - I didn't expect there to be this big of a disparity between the release and debug builds.
