### ISSUE TITLE
Cross compiling statically to aarch64 

### ISSUE THREAD

**Issue by qjerome** [VirusTotal/yara-x#185]
My project needs to embed `yara-x` library and I need to be able to cross-compile statically to `aarch64`.

So far I've been using `aarch64-unknown-linux-musl` target with `lld` linker to compile my project and it worked like a charm. However since I embedded `yara-x` it doesn't work anymore.

I get the following error:
```
= note: lld: error: unable to find library -lm
```
I do understand the error of missing `libm` yet I couldn't manage to make this cross-compilation work again !

**Comment by plusvic** [comment]
Did you set `CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=musl-gcc`  as discussed in #181?

**Comment by qjerome** [comment]
Yes indeed, I run into other issues if I do that:

```
  = note: /usr/bin/ld: /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o: error adding symbols: file in wrong format
          collect2: error: ld returned 1 exit status
```

**Comment by plusvic** [comment]
What if you create a `.cargo/config.toml` file in your project and copy the content from:

https://github.com/VirusTotal/yara-x/blob/main/.cargo/config.toml

**Comment by qjerome** [comment]
Same same, it doesn't change anything.

**Comment by qjerome** [comment]
I think you can try by yourself by trying to cross-compile `yara-x` cli, you should get the same kind of issues.

**Comment by plusvic** [comment]
Oh, now I noticed that you are talking about `aarch64`, not about `x86_64`. 

This is a bit more tricky, as you want to build a `aarch64` binary, from a `x86_64` host, and statically linked with `musl`. The problem here is cargo needs to invoke `gcc`, but it can't use the default `gcc` in your system, which produces `x86_64` binaries, it needs a cross compiler that runs on `x86_64` but targets the  `aarch64` platform. In Unbuntu you can install it with:

```
$ sudo apt-get install gcc-12-aarch64-linux-gnu
```

After that you will have a binary named `aarch64-linux-gnu-gcc-12`:

```bash
$ aarch64-linux-gnu-gcc-12 --version
aarch64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Then you must tell `cargo` where to find the linker, 

```
export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc-12
````

And also change the `CC` environment variable:

```
export CC=aarch64-linux-gnu-gcc-12
```

But then you will get an errro similar to what we already saw in #181:

```          
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0xc): undefined reference to `errno'
```

The problem here is that `aarch64-linux-gnu-gcc-12` will try to link the binary against `glibc` not `musl`. In resume:

* From a `x86_64` glibc-based host, you can a produce a `x86_64` binary that links against `musl` with `gcc-musl`
* From a `x86_64`, glibc-based host you can build an `aarch64` binary linked against `glibc` with `aarch64-linux-gnu-gcc-12`


But you are trying to build an `arch64` binary linked against `musl` from a `x86_64` glibc-based host. I'm afraid there's little I can do to help with this.

BTW, is `musl` really a requirement for you? Or all you want is a statically-linked binary?

**Comment by qjerome** [comment]
No MUSL is not a requirement, I just want a statically linked binary. I just chose MUSL because it used to work out of the box when using the proper Rust target (didn't really need anything else installed).

**Comment by plusvic** [comment]
Then try this:

```
sudo apt-get install gcc-12-aarch64-linux-gnu
export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc-12
export CC=aarch64-linux-gnu-gcc-12
export RUSTFLAGS= "-C target-feature=+crt-static" 
cargo build --target=aarch64-unknown-linux-gnu
```

I think that this should produce an `aarch64` static binary with no dependency to the system's glibc.

**Comment by qjerome** [comment]
Except the fact that it is damn slow, it works. Thanks a lot for your help
