### ISSUE TITLE
Implement std::marker::Send for Scanner

### ISSUE THREAD

**Issue by qjerome** [VirusTotal/yara-x#186]
Out of the box `yara_x::Scanner` does not support being moved within threads because it doesn't implement `std::marker::Send`.
While it is probably doable by wrapping things over a Mutex or RwLock, maybe it would be relevant to implement implement this trait in `yara-x` library to prevent any mistake on the end-user.

**Comment by plusvic** [comment]
That's intentionally. A `Scanner` can't be used simultaneously by multiple threads, if you want to scan using multiple threads, you need to create one scanner per thread (all of them can share the same compiled `Rules`, though).  That's reflected in the API by not implementing `Send`.

In order to implement `Send`, the `Scanner` would need to wrap itself in a `Mutex`, and calls to `Scanner::scan` would block until any other thread that is using the scanner finishes. That's not very helpful, and it's trivial to do in case someone wants to use the same scanner across multiple threads, which is not a very good idea anyways.

**Comment by qjerome** [comment]
Fair enough, thanks for the clarification
