### ISSUE TITLE
Feature Request: Reverse modifier

### ISSUE THREAD

**Issue by franps** [VirusTotal/yara-x#233]
I've seen multiple yara rules that detect reversed strings, as they are a common obfuscation method, for example: https://github.com/Neo23x0/signature-base/blob/master/yara/gen_transformed_strings.yar

	strings:
		/* Executables */
		$e1 = "exe.tsohcvs" fullword ascii
		$e2 = "exe.ssasl" fullword ascii
                 ...
		/* Libraries */
		$l1 = "lld.23lenreK" fullword ascii

and INDICATOR_SUSPICIOUS_EXE_ASEP_REG_Reverse

       $s1 = "nuR\\noisreVtnerruC\\swodniW\\tfosorciM" ascii wide nocase

A modifier that reverses a string could be an interesting feature to add, it's not something that can't be done manually but improves the user experience through better readability of rules.

	strings:
		/* Executables */
		$e1 = "svchost.exe" reversed fullword ascii 
		$e2 = "lsass.exe" reversed  fullword ascii
                 ...
		/* Libraries */
		$l1 = "Kernel32.dll" reversed fullword ascii

and

       $s1 = "Microsoft\\Windows\\CurrentVersion\\Run" reversed ascii wide nocase

**Comment by plusvic** [comment]
This was already discussed here: https://github.com/VirusTotal/yara/issues/1664.

The main problem with adding more modifiers is how they interact with existing ones. For instance, how a `reverse` modifier should interact with `base64`? Should the base64-encoded string be reversed? Or should we reverse the string and then encode it as base64?.

For this reason I'm not adding new modifiers that are not strictly necessary because they can be expressed with the existing features. Legibility is nice, but in this case it introduces more issues, so we better keep it simple.
