### ISSUE TITLE
Feature Request: Support for `BufReader` or On-Demand I/O for Efficient File Scanning

### ISSUE THREAD

**Issue by Benji377** [VirusTotal/yara-x#247]
Due to memory constraints in the environment planned for our application, we would like to request support for using `BufReader` as an alternative input type to `Path` and `Vec<u8>`. Alternatively, adopting on-demand I/O for file handling could address our needs.  

Our project targets low-power devices, such as Raspberry Pi, and we are currently facing challenges with archive scanning. The need to read files contained within archives entirely into memory results in a memory footprint larger than necessary, particularly for large files. Support for `BufReader` would mitigate this issue by enabling more memory-efficient file processing and allow us to scan significantly larger files without exhausting system resources.  

We would appreciate your feedback on whether this enhancement is feasible for implementation. If not, any guidance or alternative suggestions to address these constraints would be immensely helpful.  

Thank you for your consideration!

**Comment by plusvic** [comment]
Unfortunately this is not possible for a number of reasons. For instance, YARA needs to know the file size beforehand in order to evaluate the `filesize` expression, and it needs to have access to the whole content of the file when evaluating expressions that may call the `uintXX` functions, as these function can read from arbitrary offsets in the file (the offsets not always are known at compile time). Also, YARA modules need to have access to the whole file in order to parse them, for instance the `pe` module parses Windows PE files, the  `elf` module parses ELF files and so on. Some of these file formats are not designed to be parsed in a stream-oriented fashion.
